version: '3.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/
      - ./themes:/opt/keycloak/themes  # Bind mount the local themes directory
    entrypoint: [
      "/opt/keycloak/bin/kc.sh", 
      "start-dev",
      "--spi-theme-static-max-age=-1",
      "--spi-theme-cache-themes=false",
      --spi-theme-cache-templates=false
    ]

volumes:
  keycloak_data:
